[tool.black]
line-length = 100

[tool.pythonformatter.AlignAssignments]
alignment_columns = [45,57,77]

# AlignAssignmentPlugin.Plugin.ModuleLevel | AlignAssignmentPlugin.Plugin.ClassLevel | AlignAssignmentPlugin.Plugin.InitLevel
#                      1                   |                      2                  |                      4
alignment_flags = 7

[tool.pythonformatter.AlignTrailingComments]
alignment_columns = [45,57,77]
